import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { randomUUID } from 'node:crypto';
import { appendEvent, createAuditor, readEvents, runState } from '../src/registry.mjs';
import { closeServer, pipeNames, probePipe } from '../src/pipes.mjs';
import { AskOperatorSchema } from '../src/questions.mjs';
import { createTerminalizer, loadRoles, statePaths } from '../src/conductor.mjs';
import { createViewerServer, transcriptSnapshot } from '../src/viewer.mjs';

const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'conductor-r1-'));
const identity=(id=randomUUID(),attempt=1)=>({runId:id,feature:'f',role:'writer',cwd:process.cwd(),attempt});
const started=()=>{const stateDir=tmp(),runId=randomUUID(),paths=statePaths(stateDir,runId),base=identity(runId);fs.mkdirSync(paths.attempts,{recursive:true});fs.mkdirSync(paths.parks,{recursive:true});appendEvent(paths.ledger,{...base,event:'started'},{generation:1});return {stateDir,runId,paths,base}};
const instantClock=()=>{let now=0;return {now:()=>now,setTimeout(fn,ms){queueMicrotask(()=>{now+=ms;fn()});return fn},clearTimeout(){}}};

test('R1/T1 every lifecycle edge and suppressed schema is asserted',()=>{const states=['started','waiting_operator','resumed','investigate','completed','failed','cancelled'];const allowed=new Set(['started>waiting_operator','started>investigate','started>completed','started>failed','started>cancelled','waiting_operator>resumed','waiting_operator>investigate','waiting_operator>cancelled','resumed>waiting_operator','resumed>investigate','resumed>completed','resumed>failed','resumed>cancelled']);for(const from of states){for(const to of states){const f=path.join(tmp(),'l'),b=identity();if(from==='started')appendEvent(f,{...b,event:'started'},{generation:1});else if(from==='waiting_operator'){appendEvent(f,{...b,event:'started'},{generation:1});appendEvent(f,{...b,event:from},{generation:1})}else if(from==='resumed'){appendEvent(f,{...b,event:'started'},{generation:1});appendEvent(f,{...b,event:'waiting_operator'},{generation:1});appendEvent(f,{...b,event:from},{generation:2})}else{appendEvent(f,{...b,event:'started'},{generation:1});appendEvent(f,{...b,event:from,...(from==='completed'?{}:{reason:'x'})},{generation:1})}const evt={...b,event:to,...(['investigate','failed','cancelled'].includes(to)?{reason:'x'}:{})},gen=from==='waiting_operator'&&to==='resumed'?2:from==='resumed'?2:1;if(allowed.has(`${from}>${to}`))assert.doesNotThrow(()=>appendEvent(f,evt,{generation:gen}),`${from}>${to}`);else assert.throws(()=>appendEvent(f,evt,{generation:gen}),undefined,`${from}>${to}`)}}const {paths,base}=started();for(const bad of [{winnerKind:'x',suppressedKind:'y'},{generation:1,suppressedKind:'y'},{generation:1,winnerKind:'x'}])assert.throws(()=>appendEvent(paths.ledger,{...base,event:'terminalize_suppressed',...bad},{generation:1}),/invalid terminalize/)});

test('R1/T2 probe closes before dead result and EPERM/unknown fail closed',async()=>{const actual=pipeNames(tmp(),randomUUID(),'probe').lease;assert.deepEqual(await probePipe(actual),{occupied:false});const rebound=net.createServer();await new Promise((r,j)=>{rebound.once('error',j);rebound.listen(actual,r)});assert.equal((await probePipe(actual)).occupied,true);await closeServer(rebound);for(const code of ['EACCES','EPERM','WAT']){const api={createServer(){const s=new net.Server();s.listen=()=>queueMicrotask(()=>s.emit('error',Object.assign(new Error(code),{code})));return s}};await assert.rejects(probePipe('p',{netApi:api}),new RegExp(code))}const name=pipeNames('x'.repeat(500),randomUUID(),'u').lease;assert.ok(name.length<256)});

test('R1/T4 unclean park is bounded, ordered, and retains one owner token',async()=>{const {paths,base}=started(),clock=instantClock(),ops=[];const tr=createTerminalizer({paths,base,generation:1,clock,queryRef:{current:{close(){ops.push('close')},return(){return new Promise(()=>{})}}},transportObserver:{waitForExit(){ops.push('wait');return new Promise(()=>{})}}});const r=await tr.park({park:{questionId:'q'},queryClose(){assert.ok(fs.existsSync(path.join(paths.parks,'1.json')));ops.push('close')}});assert.equal(r.state,'investigate');assert.equal(r.receipt.reason,'unclean-park');assert.deepEqual(ops,['close','wait']);assert.equal(tr.winner(),'park');assert.equal(clock.now(),10_000);assert.equal(runState(readEvents(paths.ledger)),'investigate')});

test('R1/T8 complete attempt receipt preserves numbers and aggregates across attempts',async()=>{const {paths,base}=started();fs.writeFileSync(path.join(paths.attempts,'1.json'),JSON.stringify({attempt:1,sessionId:'s1',numTurns:2,durationMs:7,totalCostUsd:1.25,errors:['old']}));const tr=createTerminalizer({paths,base:{...base,attempt:2},generation:2,queryRef:{current:{close(){},return(){return Promise.resolve()}}}});appendEvent(paths.ledger,{...base,event:'waiting_operator'},{generation:1});appendEvent(paths.ledger,{...base,attempt:2,event:'resumed'},{generation:2});await tr.terminal('completed',null,{sessionId:'s2',subtype:'success',numTurns:3,durationMs:11,totalCostUsd:2.75,usage:{input_tokens:9},errors:[]});const r=JSON.parse(fs.readFileSync(paths.receipt));assert.equal(r.aggregates.attemptCount,2);assert.equal(r.numTurns,5);assert.equal(r.durationMs,18);assert.equal(r.totalCostUsd,4);assert.deepEqual(r.sessionIds,['s1','s2']);assert.ok(fs.existsSync(path.join(paths.attempts,'2.json')))});

test('R1/T9 park versus terminal has exactly one commit and complete suppression fields',async()=>{const {paths,base}=started();const tr=createTerminalizer({paths,base,generation:1,queryRef:{current:{close(){},return(){return Promise.resolve()}}}});await Promise.all([tr.park({park:{questionId:'q'}}),tr.terminal('cancelled','signal',{},'signal')]);const e=readEvents(paths.ledger),life=e.filter(x=>['waiting_operator','cancelled','investigate'].includes(x.event));assert.equal(life.length,1);const suppressed=e.find(x=>x.event==='terminalize_suppressed');assert.equal(suppressed.generation,1);assert.equal(typeof suppressed.winnerKind,'string');assert.equal(typeof suppressed.suppressedKind,'string')});

test('R1/T10 viewer reads bound SDK transcripts and enforces every answer endpoint guard',async(t)=>{const {stateDir,paths,base}=started();fs.writeFileSync(paths.manifest,JSON.stringify({feature:'f',role:'writer',canonicalCwd:process.cwd()}));appendEvent(paths.ledger,{...base,event:'session_bound',sessionId:'s1'},{generation:1});appendEvent(paths.ledger,{...base,event:'question',questionId:'q',data:{question:'Q'}},{generation:1});const seen=[];const snap=await transcriptSnapshot(stateDir,{sessionReader:async(id,o)=>{seen.push([id,o.dir]);return [{type:'assistant'}]}});assert.deepEqual(seen,[['s1',process.cwd()]]);assert.equal(snap.runs[0].transcripts[0].messages.length,1);const s=createViewerServer({stateDir,sessionReader:async()=>[]});t.after(()=>s.close());await new Promise(r=>s.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${s.address().port}/api/answer`,post=(body,headers={})=>fetch(url,{method:'POST',headers:{'content-type':'application/json',...headers},body});assert.equal((await post('{}')).status,403);assert.equal((await post('{}',{'x-conductor':'1',origin:'https://evil.test'})).status,403);assert.equal((await post(JSON.stringify({questionId:'bad',text:'x'}),{'x-conductor':'1'})).status,409);assert.equal((await post(JSON.stringify({questionId:'q',text:'x'}),{'x-conductor':'1'})).status,201);assert.equal((await post(JSON.stringify({questionId:'q',text:'x'}),{'x-conductor':'1'})).status,409);assert.equal((await post('x'.repeat(65537),{'x-conductor':'1'})).status,413)});

test('R1/T13 every UTF-8 payload boundary is exact and missing denial IDs never dedupe',()=>{const bytes=n=>'é'.repeat(n/2);for(const [key,max] of [['question',4096],['context',8192]]){assert.equal(AskOperatorSchema.safeParse({question:'q',[key]:bytes(max)}).success,true);assert.equal(AskOperatorSchema.safeParse({question:'q',[key]:`${bytes(max)}x`}).success,false)}assert.equal(AskOperatorSchema.safeParse({question:'q',options:Array(16).fill(bytes(200))}).success,true);assert.equal(AskOperatorSchema.safeParse({question:'q',options:Array(17).fill('x')}).success,false);assert.equal(AskOperatorSchema.safeParse({question:'q',options:[`${bytes(200)}x`]}).success,false);const {paths,base}=started(),audit=createAuditor(paths.ledger,base,{generation:1});audit(undefined,'PreToolUse','Write','deny');audit(undefined,'PreToolUse','Write','deny');const d=readEvents(paths.ledger).filter(e=>e.event==='denial');assert.equal(d.length,2);assert.ok(d.every(e=>e.failClosed&&e.reason.startsWith('missing-tool-use-id')))});

test('R1/T6 gated inventory is policy-derived, not role supplied',()=>{const dir=tmp(),file=path.join(dir,'roles.json');fs.writeFileSync(file,JSON.stringify({x:{tools:[],allowedTools:['Write'],gatedTools:[]}}));assert.throws(()=>loadRoles(file),/gated tool/)});
