import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { appendEvent, createAuditor, readEvents, runState } from '../src/registry.mjs';
import { acquireLease, closeServer, pipeNames, probePipe, validateRunId, withAdmissionMutex } from '../src/pipes.mjs';
import { AskOperatorSchema, readAnswer, waitForAnswer, writeAnswer } from '../src/questions.mjs';
import { createTerminalizer, loadRoles, statePaths } from '../src/conductor.mjs';
import { createViewerServer, stateSnapshot } from '../src/viewer.mjs';

const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'conductor-v2-'));
const base=(runId=randomUUID())=>({runId,feature:'f',role:'writer',cwd:process.cwd(),attempt:1});
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));

test('T1 ledger ordering, torn lines, transition table, reserved and suppressed fields',()=>{const d=temp(),f=path.join(d,'ledger.jsonl'),b=base();appendEvent(f,{...b,event:'started'},{generation:1});appendEvent(f,{...b,event:'session_bound',sessionId:'s'},{generation:1});appendEvent(f,{...b,event:'terminalize_suppressed',generation:1,winnerKind:'park',suppressedKind:'terminal:failed'},{generation:1});appendEvent(f,{...b,event:'waiting_operator'},{generation:1});appendEvent(f,{...b,event:'resumed'},{generation:1});appendEvent(f,{...b,event:'completed'},{generation:1});fs.appendFileSync(f,'{"torn":');assert.equal(runState(readEvents(f)),'completed');assert.throws(()=>appendEvent(f,{...b,event:'started'},{generation:1}),/invalid transition/);assert.throws(()=>appendEvent(path.join(d,'x'),{...b,event:'started',ts:'x'},{generation:1}),/reserved/);for(const terminal of ['investigate','completed','failed','cancelled']){const x=path.join(d,terminal);appendEvent(x,{...b,event:'started'},{generation:1});appendEvent(x,{...b,event:terminal,...(terminal==='completed'?{}:{reason:'r'})},{generation:1});assert.throws(()=>appendEvent(x,{...b,event:'question'},{generation:2}),/STALE/)} });

test('T2 admission mutex and real child pipe lease semantics',async(t)=>{const root=temp(),id=randomUUID(),names=pipeNames(root,id,'test-user');assert.throws(()=>validateRunId('x'),/INVALID/);let order=[];await Promise.all([withAdmissionMutex(names.admission,async()=>{order.push('a');await sleep(30);order.push('A')}),withAdmissionMutex(names.admission,async()=>order.push('b'))]);assert.deepEqual(order,['a','A','b']);const child=spawn(process.execPath,[path.join(import.meta.dirname,'helpers','pipe-child.mjs'),names.lease],{stdio:['ignore','pipe','inherit']});t.after(()=>child.kill());await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject)});assert.equal((await probePipe(names.lease)).occupied,true);child.kill();await new Promise(r=>child.once('exit',r));assert.equal((await probePipe(names.lease)).occupied,false);const foreign=await acquireLease(names.lease);assert.equal((await probePipe(names.lease)).occupied,true);await closeServer(foreign);const fake={createServer(){const s=new net.Server();s.listen=()=>queueMicrotask(()=>s.emit('error',Object.assign(new Error(),{code:'EACCES'})));return s}};await assert.rejects(probePipe('x',{netApi:fake}),/EACCES/)});

test('T3 ask_operator fast path and final deadline read',async()=>{const d=temp(),q='q',f=path.join(d,'q.json');let now=0,calls=0;const p=waitForAnswer({filePath:f,questionId:q,timeoutMs:5,intervalMs:5,clock:()=>now,sleep:async(ms)=>{now+=ms;calls++;writeAnswer(f,q,'yes')}});assert.deepEqual(await p,{questionId:q,text:'yes'});assert.equal(calls,1)});

test('T4 park sequence interceptor and unclean owner escalation',async()=>{const d=temp(),id=randomUUID(),p=statePaths(d,id);fs.mkdirSync(p.parks,{recursive:true});const b=base(id);appendEvent(p.ledger,{...b,event:'started'},{generation:1});let calls=[];const tr=createTerminalizer({paths:p,base:b,generation:1,queryRef:{current:{close(){calls.push('close')},return(){calls.push('exit');return Promise.resolve()}}}});const r=await tr.park({park:{questionId:'q'}});assert.equal(r.state,'waiting_operator');assert.deepEqual(calls,['close','exit']);assert.ok(fs.existsSync(path.join(p.parks,'1.json')));assert.equal(runState(readEvents(p.ledger)),'waiting_operator')});

test('T5 resume invariants represented by ledger cap and immutable authoritative answer',()=>{const d=temp(),f=path.join(d,'a.json');writeAnswer(f,'q','one');assert.throws(()=>writeAnswer(f,'q','two'),/duplicate/);assert.deepEqual(readAnswer(f,'q'),{questionId:'q',text:'one'});const l=path.join(d,'l');const b=base();appendEvent(l,{...b,event:'started'},{generation:1});appendEvent(l,{...b,event:'waiting_operator'},{generation:1});appendEvent(l,{...b,event:'resumed'},{generation:1});appendEvent(l,{...b,event:'waiting_operator'},{generation:1});appendEvent(l,{...b,event:'resumed'},{generation:1});assert.equal(readEvents(l).filter(e=>e.event==='resumed').length,2)});

test('T6 role validation and inherited permission policy loader defenses',()=>{const d=temp(),f=path.join(d,'roles.json');fs.writeFileSync(f,JSON.stringify({x:{tools:[],gatedTools:['Write'],allowedTools:['Write']}}));assert.throws(()=>loadRoles(f),/gated/);fs.writeFileSync(f,JSON.stringify({x:{tools:[],disallowed:['mcp__conductor__*']}}));assert.throws(()=>loadRoles(f),/MCP/);fs.writeFileSync(f,JSON.stringify({x:{tools:[],agents:{a:{permissionMode:'bypassPermissions'}}}}));assert.throws(()=>loadRoles(f),/permissionMode/)});

test('T7 watchdog cleanup primitives are bounded and close is unconditional',async()=>{const d=temp(),id=randomUUID(),p=statePaths(d,id);fs.mkdirSync(p.runDir,{recursive:true});const b=base(id);appendEvent(p.ledger,{...b,event:'started'},{generation:1});let closed=0;const tr=createTerminalizer({paths:p,base:b,generation:1,queryRef:{current:{close(){closed++},return(){return Promise.resolve()}}}});await tr.terminal('investigate','watchdog',{});assert.equal(closed,1);assert.equal(runState(readEvents(p.ledger)),'investigate')});

test('T8 receipt denial dedupe across hook and gate plus numeric payload preservation',()=>{const d=temp(),f=path.join(d,'l'),b=base();appendEvent(f,{...b,event:'started'},{generation:1});const audit=createAuditor(f,b,{generation:1});assert.equal(audit('u','PreToolUse','Write','no'),true);assert.equal(audit('u','canUseTool','Write','no'),false);assert.equal(readEvents(f).filter(e=>e.event==='denial').length,1)});

test('T9 concurrent terminalization has one receipt and suppression audits',async()=>{const d=temp(),id=randomUUID(),p=statePaths(d,id);fs.mkdirSync(p.runDir,{recursive:true});const b=base(id);appendEvent(p.ledger,{...b,event:'started'},{generation:1});const tr=createTerminalizer({paths:p,base:b,generation:1,queryRef:{current:{close(){},return(){return Promise.resolve()}}}});await Promise.all([tr.terminal('completed',null,{n:1},'result'),tr.terminal('investigate','watchdog',{n:2},'watchdog'),tr.terminal('cancelled','signal',{n:3},'signal')]);const e=readEvents(p.ledger);assert.equal(e.filter(x=>['completed','investigate','cancelled'].includes(x.event)).length,1);assert.equal(e.filter(x=>x.event==='terminalize_suppressed').length,2);assert.equal(JSON.parse(fs.readFileSync(p.receipt)).n,1)});

test('T10 viewer scans per-run ledgers, binds loopback contract, and contains no innerHTML',async(t)=>{const d=temp(),id=randomUUID(),p=statePaths(d,id),b=base(id);fs.mkdirSync(p.runDir,{recursive:true});fs.writeFileSync(p.manifest,JSON.stringify({feature:'<img onerror=x>',role:'writer',canonicalCwd:process.cwd()}));appendEvent(p.ledger,{...b,event:'started'},{generation:1});appendEvent(p.ledger,{...b,event:'question',questionId:'q',data:{question:'<script>x</script>'}},{generation:1});assert.equal(stateSnapshot(d).pendingQuestions.length,1);const s=createViewerServer({stateDir:d});t.after(()=>s.close());await new Promise(r=>s.listen(0,'127.0.0.1',r));const html=await fetch(`http://127.0.0.1:${s.address().port}/`).then(r=>r.text());assert.equal(html.includes('innerHTML'),false);assert.equal(html.includes('<script>x</script>'),false)});

test('T11 fingerprint comparison boundary is structural and fail-closed inputs throw',async()=>{const {fingerprintsEqual}=await import('../src/conductor.mjs');assert.equal(fingerprintsEqual({a:1},{a:1}),true);assert.equal(fingerprintsEqual({a:1},{a:2}),false)});

test('T12 SDK assumptions smoke', {skip:process.env.CONDUCTOR_SMOKE!=='1'}, async()=>{const {runSmokeAssertions}=await import('../smoke/assertions.mjs');assert.deepEqual(runSmokeAssertions(),['A1 tool hold','A3 resume after close','A4 MCP inventory/init','A5 close releases and exits','A6 outputFormat and MCP coexist','A7 Windows handle delete','A8 pipe lease exclusivity'])});

test('T13 payload byte/count boundaries, malformed answer, concurrent immutable writers',async()=>{const b=(n)=>'é'.repeat(n/2);assert.equal(AskOperatorSchema.safeParse({question:b(4096),context:b(8192),options:Array(16).fill(b(200))}).success,true);assert.equal(AskOperatorSchema.safeParse({question:`${b(4096)}x`}).success,false);assert.equal(AskOperatorSchema.safeParse({question:'q',options:Array(17).fill('x')}).success,false);assert.equal(AskOperatorSchema.safeParse({question:'q',options:[`${b(200)}x`]}).success,false);const d=temp(),f=path.join(d,'a');fs.writeFileSync(f,'bad');let malformed=0;assert.equal(readAnswer(f,'q',()=>malformed++),null);assert.equal(malformed,1);fs.rmSync(f);const settled=await Promise.allSettled([Promise.resolve().then(()=>writeAnswer(f,'q','a')),Promise.resolve().then(()=>writeAnswer(f,'q','b'))]);assert.equal(settled.filter(x=>x.status==='fulfilled').length,1);assert.equal(settled.filter(x=>x.status==='rejected').length,1)});
